# Ruta al archivo de configuración del modelo
config_file: "./configs/diffdet.densea.swintinyv1.yaml"

# Ruta a los pesos del modelo entrenado
model_weights: "/app/DiffusionDet/Densea/output/swintiny_densea_v1/model_final.pth"

# Umbral de confianza para filtrar detecciones
confidence_threshold: 0.5

# Umbral de IoU para considerar una detección como positiva
iou_thresh: 0.5

# Nombre del conjunto de datos registrado para evaluación
dataset_name: "cleansea/test"

# Directorio donde se guardarán los resultados y visualizaciones
output_dir: "./output/evaluation/swintiny_densea_v1"

# Ruta al directorio raíz de los datos
data_root: "./datasets"

# Lista de clases (asegúrate de que coincidan con las de tus datasets)
classes:
  - "background"
  - "Can"
  - "Squared_Can"
  - "Wood"
  - "Bottle"
  - "Plastic_Bag"
  - "Glove"
  - "Fishing_Net"
  - "Tire"
  - "Packaging_Bag"
  - "WashingMachine"
  - "Metal_Chain"
  - "Rope"
  - "Towel"
  - "Plastic_Debris"
  - "Metal_Debris"
  - "Pipe"
  - "Shoe"
  - "Car_Bumper"
  - "Basket"

# Opcional: Lista de opciones adicionales para la configuración de detectron2
opts:
  - "MODEL.DEVICE"
  - "cuda"

# Opcional: Guardar visualizaciones de las detecciones (True o False)
save_visualizations: True
