version: '3.8'

services:
  diffusiondet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diffusiondet_container
    volumes:
      - ./datasets:/app/datasets
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PORT=8888
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]
    command: ["/bin/bash"]
