_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
    FREEZE_AT: 0
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3" ]
  DiffusionDet:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 20
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ("cleansea_train","synthetic_v1",)
  TEST:  ("cleansea_test",)
SOLVER:
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  IMS_PER_BATCH: 4
  MAX_ITER: 50000
  STEPS: (35000, 45000)
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "./output/swinbase_densea_v2"