_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ("cleansea_train",)
  TEST:  ("cleansea_test",)
SOLVER:
  STEPS: (350000, 420000)
  MAX_ITER: 450000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
