_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  #WEIGHTS: "models/torchvision-R-101.pkl"
  WEIGHTS: "output/resnet-101_cleansea+synth/model_0012999.pth"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 20
  MASK_ON: True
DATASETS:
  TRAIN: ("cleansea_train","synthetic_dataset_v2_train",)
  TEST:  ("cleansea_test","synthetic_dataset_v2_test",)
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  STEPS: (5000, 15000, 30000) # The iteration number to decrease learning rate by GAMMA.
  MAX_ITER: 35000
  IMS_PER_BATCH: 4
  BASE_LR: 0.0025
  CHECKPOINT_PERIOD: 500
  OPTIMIZER: SGD
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "./output/resnet-101_cleansea+synth"