_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 20
  MASK_ON: False
DATASETS:
  TRAIN: ("cleansea_train",)
  TEST:  ("cleansea_test",)
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  STEPS: (1000, 2000, 3000, 5000, 10000, 15000) # The iteration number to decrease learning rate by GAMMA.
  MAX_ITER: 20000
  IMS_PER_BATCH: 4
  BASE_LR: 0.0025
  CHECKPOINT_PERIOD: 500
  OPTIMIZER: SGD
TEST:
  EVAL_PERIOD: 500