_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  ROI_HEADS:
    NUM_CLASSES: 20
  DiffusionDet:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 20
  MASK_ON: True
DATASETS:
  TRAIN: ("cleansea_train","synthetic_dataset_v1",)
  TEST:  ("cleansea_test",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  STEPS: (2000, 4000, 7000, 17000) # The iteration number to decrease learning rate by GAMMA.
  MAX_ITER: 20000
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "./output/resnet-50v2_cleansea+synth"