_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3" ]
  DiffusionDet:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 20
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ("cleansea_train",)
  TEST:  ("cleansea_test",)
SOLVER:
  STEPS: (10000, 15000, 30000) # The iteration number to decrease learning rate by GAMMA.
  MAX_ITER: 40000
  IMS_PER_BATCH: 1
  BASE_LR: 0.0025
  CHECKPOINT_PERIOD: 1000
  OPTIMIZER: SGD
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "./output/swinbase_densea"