_BASE_: "Base-DiffusionDet.yaml"

MODEL:
  WEIGHTS: "models/swin_small_patch4_window7_224.pth"  # Actualizar a pesos de Swin Small
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
    FREEZE_AT: 0
  SWIN:
    SIZE: S  # Cambiado a Swin Small
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3" ]
  DiffusionDet:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 20
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 20
    BATCH_SIZE_PER_IMAGE: 256
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]

DATASETS:
  TRAIN: ("cleansea_train", "synthetic_v1",)
  TEST:  ("cleansea_test",)

DATALOADER:
  NUM_WORKERS: 6

SOLVER:
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.0001  # Reducir la tasa de aprendizaje para Swin Small
  WEIGHT_DECAY: 0.05
  IMS_PER_BATCH: 4  # Aumentar el tamaño de lote debido al menor consumo de memoria
  MAX_ITER: 45000  # Ajustar el número de iteraciones
  STEPS: (30000, 40000)
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 1.0
  
  AMP:
    ENABLED: False
  
TEST:
  EVAL_PERIOD: 5000
  
OUTPUT_DIR: "./output/swinsmall_densea_v1"
