_BASE_: "Base-DiffusionDet.yaml"
VERSION: 2
MODEL:
  BACKBONE:
    FREEZE_AT: 1
  #WEIGHTS: "models/torchvision-R-101.pkl"
  WEIGHTS: "output/resnet-101v5_cleansea+synth/model_0001499.pth"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 20
  ROI_HEADS:
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ("cleansea_train","synthetic_dataset_v1",)
  TEST:  ("cleansea_test",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  STEPS: (1000, 2000, 4000, 7000, 17000) # The iteration number to decrease learning rate by GAMMA.
  MAX_ITER: 20000
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  CHECKPOINT_PERIOD: 500
  OPTIMIZER: SGD
  WARMUP_ITERS: 1000
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0025
  WEIGHT_DECAY_NORM: 0.0
  GAMMA: 0.1  # Factor de decaimiento de la tasa de aprendizaje
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "./output/resnet-101v5_cleansea+synth"