_BASE_: "Base-DiffusionDet.yaml"

MODEL:
  WEIGHTS: "models/swin_tiny_patch4_window7_224.pth"  # Pesos pre-entrenados de Swin Tiny
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
    FREEZE_AT: 0  # Entrenar todas las capas
  SWIN:
    SIZE: T  # Indica Swin Tiny
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3"]
  DiffusionDet:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 20
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 20
    BATCH_SIZE_PER_IMAGE: 256  # Reducido para disminuir el tiempo de cómputo
    SCORE_THRESH_TEST: 0.5
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]

DATASETS:
  TRAIN: ("cleansea_train", "synthetic_v1",)
  TEST: ("cleansea_test",)

DATALOADER:
  NUM_WORKERS: 0  # Ajusta según tu CPU

INPUT:
  MIN_SIZE_TRAIN: (512,)  # Reducir la resolución de entrada
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 640

SOLVER:
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.0001  # Tasa de aprendizaje inicial
  WEIGHT_DECAY: 0.05
  IMS_PER_BATCH: 4  # Tamaño de lote reducido para ajustarse a la memoria
  MAX_ITER: 45000  # Reducido para acelerar el entrenamiento
  STEPS: (30000, 40000)  # Ajustar los pasos de reducción de LR
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 1000  # Guardar puntos de control menos frecuentes
  GAMMA: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 1.0

  AMP:
    ENABLED: False  # Activar AMP para acelerar el entrenamiento y reducir uso de memoria

TEST:
  EVAL_PERIOD: 5000  # Evaluar menos frecuentemente para ahorrar tiempo

OUTPUT_DIR: "./output/swintiny_densea_v1"
